---
name: Test
on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create release
        uses: shogo82148/actions-create-release@v1.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: main
          release_name: main
          draft: false
          prerelease: false
          overwrite: true
          
      - run: npm i
      - uses: ./
        with:
          repository: nmbgeek/github-action-get-latest-commit
      - uses: ./
        with:
          owner: nmbgeek
          repo: github-action-get-latest-commit
      - uses: ./
        with:
          owner: nmbgeek
          repo: github-action-get-latest-commit
          branch: main
      - uses: ./
        with:
          repository: nmbgeek/github-action-get-latest-commit
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          owner: nmbgeek
          repo: github-action-get-latest-commit
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./
        with:
          owner: nmbgeek
          repo: github-action-get-latest-commit
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}
